AWSTemplateFormatVersion: "2010-09-09"
Transform: "AWS::Serverless-2016-10-31"
Description: "application for slack app example"
Parameters:
  SlackSigningSecret:
    Type: String
    NoEcho: true
  BotUserAccessToken:
    Type: String
    NoEcho: true
  EnvironmentEncryptionKeyArn:
    Type: String
    Default: ""
  DefaultChannelID:
    Type: String
Conditions:
  AllowPlaintextEnvironment: !Equals [ !Ref EnvironmentEncryptionKeyArn, "" ]
Resources:
  SlashCommand:
    Type: AWS::Serverless::Function
    Properties:
      Handler: slash
      Runtime: go1.x
      CodeUri: ../build/slash
      Environment:
        Variables:
          SLACK_SIGNING_SECRET: !Ref SlackSigningSecret
          BOT_USER_ACCESS_TOKEN: !Ref BotUserAccessToken
          DEFAULT_CHANNEL_ID: !Ref DefaultChannelID
      KmsKeyArn: !If [ AllowPlaintextEnvironment, !Ref AWS::NoValue, !Ref EnvironmentEncryptionKeyArn]
      Events:
        HttpPost:
          Type: Api
          Properties:
            Path: '/slash'
            Method: post
  EventReceiver:
    Type: AWS::Serverless::Function
    Properties:
      Handler: event
      Runtime: go1.x
      CodeUri: ../build/event
      Environment:
        Variables:
          SLACK_SIGNING_SECRET: !Ref SlackSigningSecret
          BOT_USER_ACCESS_TOKEN: !Ref BotUserAccessToken
          DEFAULT_CHANNEL_ID: !Ref DefaultChannelID
      KmsKeyArn: !If [ AllowPlaintextEnvironment, !Ref AWS::NoValue, !Ref EnvironmentEncryptionKeyArn]
      Events:
        HttpPost:
          Type: Api
          Properties:
            Path: '/event'
            Method: post
  InteractiveReceiver:
    Type: AWS::Serverless::Function
    Properties:
      Handler: interactive
      Runtime: go1.x
      CodeUri: ../build/interactive
      Environment:
        Variables:
          SLACK_SIGNING_SECRET: !Ref SlackSigningSecret
          BOT_USER_ACCESS_TOKEN: !Ref BotUserAccessToken
          DEFAULT_CHANNEL_ID: !Ref DefaultChannelID
      KmsKeyArn: !If [ AllowPlaintextEnvironment, !Ref AWS::NoValue, !Ref EnvironmentEncryptionKeyArn]
      Events:
        HttpPost:
          Type: Api
          Properties:
            Path: '/interactive'
            Method: post
Outputs:
  ProdDataEndpoint:
    Description: "API Prod stage endpoint"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
